name:                vehicle
version:             0.1.0.0
github:              "wenkokke/vehicle"
license:             BSD3
author:              "Wen Kokke"
maintainer:          "wenkokke@users.noreply.github.com"
copyright:           "© Wen Kokke"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/wenkokke/vehicle#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src/hs

executables:
  vehicle-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vehicle

tests:
  vehicle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vehicle
