name: Vehicle test suite

on: [push]

env:
  GHC_VERSION: 8.10.3
  STACK_VERSON: 2.5.1

jobs:
  install:
    name: Install Vehicle and run test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out code
        uses: actions/checkout@v2

      - name: Cache stack packages
        uses: actions/cache@v2
        id: cache-cabal
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ env.GHC_VERSION }}-${{ env.STACK_VERSION }}

      - name: Install Haskell and Stack
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ env.GHC_VERSION }}
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          enable-stack: true
          stack-version: latest

      - name: Setup stack
        run: cp stack-${{ env.GHC_VERSION }}.yaml stack.yaml

      - name: Install dependencies
        run: stack install BNFC

      - name: Run test suite
        run: make test